.TH hwp2txt 1 "30 May 2014"
.SH NAME
hwp2txt \- hwp document to text converter
.SH SYNOPSIS
.B hwp2txt
[OPTIONS]
.I HWP_FILE
.SH DESCRIPTION
converts hwp document file to plain text.
.PP
The
.I HWP_FILE
argument is mandatory.
.SH OPTIONS
.TP
.B \-o, \-\-output\fR=\fIFILE\fR
Write output to \fIFILE\fR and not to standard output.
.TP
.B \-h, \-\-help
Print usage information.
.SH "SEE ALSO"
.BR hwp2pdf (1),
.BR hwp2svg (1),
.BR unhwp (1)
