.TH hwp2svg 1 "30 May 2014"
.SH NAME
hwp2svg \- hwp document to svg converter
.SH SYNOPSIS
.B hwp2svg
[OPTIONS]
.I HWP_FILE
.SH DESCRIPTION
converts hwp document file to svg file.
.PP
The
.I HWP_FILE
argument is mandatory.
.SH OPTIONS
.TP
.B \-o, \-\-output\fR=\fISVG_DIRECTORY\fR
Write output to \fISVG_DIRECTORY\fR and not to standard output.
.TP
.B \-h, \-\-help
Print usage information.
.SH "SEE ALSO"
.BR hwp2pdf (1),
.BR hwp2txt (1),
.BR unhwp (1)
